version: '3.8'

services:
  # Der PostgreSQL-Datenbank-Service
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: csv_imports
    ports:
      - "5432:5432" # Leitet den DB-Port an den Host weiter (optional, f端r Debugging)
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistenter Speicher f端r die DB-Daten

  # Der Python-Importer-Service
  importer:
    build: . # Baut das Image aus dem Dockerfile im aktuellen Verzeichnis
    container_name: python_importer
    depends_on:
      - db # Stellt sicher, dass die DB gestartet ist, bevor der Importer startet
    environment:
      # Umgebungsvariablen f端r das Python-Skript
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=csv_imports
      - DB_HOST=db # Der Hostname ist der Name des DB-Services
      - DB_PORT=5432
    volumes:
      # Mountet die CSV-Datei in den Container, damit das Skript sie lesen kann
      - ./ihre_daten.csv:/app/ihre_daten.csv

volumes:
  postgres-data: # Definiert das Volume f端r die Persistenz
