version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: csv_imports
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d csv_imports"]
      interval: 5s
      timeout: 5s
      retries: 5

  csv-importer:
    build: .
    container_name: csv_importer
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: csv_imports
    volumes:
      - ./data:/app/data  # Mount für CSV-Dateien
    command: ["python", "main.py", "sample_csv.csv"]

volumes:
  postgres-data: